name = "Overwaifu"
license = "MIT"
licenselink = "https://github.com/overwaifu/hugo-overwaifu-theme/blob/master/LICENSE"
description = "Hugo theme for OverWaifu.moe"
homepage = "https://overwaifu.moe"
tags = ["overwaifu", "responsive", "flexbox"]
min_version = "0.37"

[author]
  name = "Leonid Boykov"
  homepage = "https://leonidboykov.com"

